linters:
  - header:
      extra: []
      shebang: '#!/usr/bin/env python3'
  - import:
      packages: ['roberto']
  - pylint:
      config: .pylintrc
  - pycodestyle:
      config: .pycodestylerc
  - autopep8:
      config: .pycodestylerc
      line-range: [79, 100]
  - pydocstyle:
      config: .pydocstylerc
  - whitespace:
  - yamllint:
      filefilter: ['- *conda.recipe/meta.yaml', '+ *.yml', '+ *.yaml']
