linters:
  - header:
      extra: []
      shebang: '#!/usr/bin/env python3'
  - import:
      packages: ['roberto']
  - pylint:
      config: .pylintrc
  - pycodestyle:
      config: .pycodestylerc
  - pydocstyle:
      config: .pydocstylerc
  - whitespace:
  - yamllint:
