linters:
  - header:
      extra: []
      shebang: '#!/usr/bin/env python3'
  - import:
      packages: ['roberto']
  - pylint:
      config: .pylintrc
  - pycodestyle:
      config: .pycodestylerc
  - pydocstyle:
      config: .pydocstylerc
  - whitespace:
  - yamllint:
      # meta.yaml is excluded because it contains jinja templating codes
      filefilter: ['- */meta.yaml', '+ *.yaml', '+ *.yml']
