linters:
  - import:
      packages: ['roberto']
  - pylint:
      config: .pylintrc
  - pycodestyle:
      config: .pycodestylerc
  - pydocstyle:
      config: .pydocstylerc
  - whitespace:
  - yamllint:
