project:
  name: roberto
  packages:
    - conda_name: roberto
      name: roberto
      path: .
      tools:
        - write-py-version
        - cardboardlint-static
        - pytest
        - cardboardlint-dynamic
        - build-sphinx-doc
        - upload-docs-gh
        - build-py-source
        - build-conda
        - deploy-pypi
        - deploy-conda
        - deploy-github
