matrix:
  include:
    - os: linux
      dist: xenial
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.6"
        - ROBERTO_DEPLOY_BINARY=1
    - os: linux
      dist: xenial
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.7"
        - ROBERTO_DEPLOY_NOARCH=1
        - ROBERTO_DEPLOY_BINARY=1
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.6"
        - ROBERTO_DEPLOY_BINARY=1
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.7"
        - ROBERTO_DEPLOY_BINARY=1

env:
  global:
    # Install conda in a *sub*directory of a directory cached by travis.
    - ROBERTO_CONDA_BASE_PATH=${HOME}/cache/miniconda3
    # Roberto does not need to upload coverage. We will generate more coverage
    # reports and upload them manually instead.
    # - ROBERTO_UPLOAD_COVERAGE=1
    # Build conda packages outside the miniconda tree, to avoid caching.
    # This makes it possible to still deploy packages after cache cleaning.
    - CONDA_BLD_PATH=${HOME}/conda-bld
    # Tell roberto which branch is being merged into, in case of a PR.
    - ROBERTO_MERGE_BRANCH=$(TRAVIS_BRANCH)

    # GITHUB_TOKEN
    # yamllint disable-line rule:line-length
    - secure: "kHLuS7Znf25Zv0hYRYyHlZEV0X78Dcm6JyfCO0txokEZ/cNaxj/WknAmLVe9QYVx53LJ5pYS+3bL2eZiK3eop5SrriXnjc6P2miB5AAMcZI7o7WAiE6ov3I7SH/pg6ExZ599RG+nTOEQG7Ppio28SQSVMzu/jXHEzL/SY+UsYMAM/m4wSvfoTOgk60lm+EjBI27QGI+ZLbAvMUmHtWWSTTUAU4XgPWNEVIAyVOcFuEknKtjXOmfIF8nRi4Qfg0tCBpfuS762fag8sPpu6O/Vw8XA/ckFyfD2tCP2nOjc8fDfWm66VoDBu/Vm3IZ7Q1nacHezXqXBN3E+7SqMVWtk2LrVIhGx3eedkvPxMqIjU65mG6Xf+3PM1lB52+IJWbEC1OMVD8Z6UfmuCbKbO5d4dYyYUrQh6ASmPHumCaEB5Uf4FWWrcASgSbsdrFn7VfVE0BTPeZ7OVXV/imBRvGPZLoTnb5v08uzqf0VjBit4ZBiZLAc2yiL8UFZUG+V66w8jcG2/1s9zRISEHDcynnU1QkzPTyp0JdI5OPAWLdCxdi0P2EA/f3MjhYrujB6urYPVKISe+Rnwc81zXZANdYUuo6n6VMP1VIQPWO9fS5LVO7H9CyqBwNrpGwkCF0HoXuxG/JD/jn2KBBLJHmaXgGrjY8V4soAD5BFGP2Z0b3w3Pz4="
    # ANACONDA_API_TOKEN
    # yamllint disable-line rule:line-length
    - secure: "ie+hspA2SV6eNsX12R84Yk3twT50LwX2p9qI1mIO3LzNLDON88X1zrU/k9uPX1h0tVHTp0gWycdg1g8bQOAsw8h75b6sdLWfWyaNTdP+z2V2daUvF9nLeA22GNDBv6/zlUCGD9n2F7HMQvqhGRa/rPPFX2aVS7QWZU3+WfDrxD09g8gzpdI3LfIk6TxgVXSXZRCwFYxuksnn3R0Hn1HVpHc3NHYNFg1KMG3+4zZluTSkDxJ7uW+8UEGmFfOmICk0J5izLm497KIeB7nrzw1gvMPQ9Y/rigxyIIazKl74dSl34SlCrt08ubcCf8cO9+Ci7SYQrIbfeILiGtDJaT056cc4yw18ryTsCcmGyLHbvguKeRTamkgb+flpA0Ry68iaZAP3CFzXYY+3lNe7DJ0Em60EBz1wfor1+k8GjKgZLv777i3vpND8R0eP9K3vfXYvcdfsYScya1Qh7zHeM/YrWar9hz0nCizoLhYab6jpj8MkygrV+vdDESiBrjhBo4UiYoYIngE/yNyKIixpheQwWYpGFXB7mWZlxnZg9mhBMnY7E6xqC15hOZGySTwdUhyS5hRfNNVePR/wZSoRfYkZdBGquP5so5vJyBZhiRcw2B7Qbz9jnsztN5QuexePBFxwCuVkz+l38RmGtRQ4izSC+6hCmHwa0vhIyQjX0tl9mmA="
    # TWINE_PASSWORD
    # yamllint disable-line rule:line-length
    - secure: "jlhDSD7sy8vXmdnLZokDTSrqX92oZxAA8Y+Z33mbefISGXsyi+JXprQ0dhOhp2Y7ZpzQT4YlQLHJxH5uc1v493eN6JFin1NsHknpDAaH42OXZHTGoQyuf5zZAtorD/VjuPtQmAPLksu7aIid24RG4qwRl3og9F7UCDs/QnFyPQMw84Xm5brMsNpANyROj5S8qNWk4/GARqr3Lzsq/SG5prXDgrO+FrCkS5OpjZTikDB7/8Ptp3YytgWQVl9RrA0RhFJiBLiVLXupxhLqxu84XFshesuPocFIxTe8jHbDZTQd49mBjDm6DfRQJNxgjg5CvMn+njRrP5aXwcxKM6zd21Vfcl1AoApP5Qd4f1ZUYEPjDm0ax6ipdKu/af4P/fCy99z/S2/Yxmh9JxPu65QqKBV4YEEy1BcflZLdKK3Syz0khspWoMGvDHdVKfcmOmvYQkmuH/QezEPPl49raOfPx8t+oW4nUEWMotMTFkFS9F/ahiKgjlxtLK5ZIIg5clo1gS0XfL85phm+NGBprbVd92JytUm1n/1F4eYquh0d6BRKYffV6ASMSOse5iadNmr30nQy2JIxzf65iZ8zYeYewLH4WOP6SjwkVGDnsRwemOU8oiXGP9EJqW0B3xkCGTj56e7WA7Hga5MUPRw2rYhSCX7c8IVUlf+z2yrG0Xs2Zwo="
    - TWINE_USERNAME: theochem

cache:
  directories:
    - ${HOME}/cache

install:
  # Disable deployment when TRAVIS_TAG is not set. This avoids duplicate deployments.
  - >-
    if [[ -z $TRAVIS_TAG ]]; then
      export ROBERTO_DEPLOY_BINARY=0 ROBERTO_DEPLOY_NOARCH=0;
    fi
  # Get a basic python 3 with pip to run roberto
  - python3 --version
  # TODO check if this is still needed
  - wget --no-clobber -O ${HOME}/cache/get-pip.py https://bootstrap.pypa.io/get-pip.py || true
  - python3 ${HOME}/cache/get-pip.py --user
  # Normally roberto should be installed from pypi, but roberto can take a shortcut.
  # We also need to install coverage because of cov analysis on the whole self test.
  - python3 -m pip install . coverage --user

script:
  # Instead of simply calling `rob`, we do something that always works on osx too.
  # Moreover, we add coverage to measure which parts got used, not just for
  # unit tests.
  # Adding sleep trick to avoid potential output truncation issues.
  #     See https://github.com/travis-ci/travis-ci/issues/6018
  - python3 -m coverage run --branch --source=roberto -m roberto && sleep 10
  # Report and upload also the additional coverage.
  - python3 -m coverage report -m
  - python3 -m coverage xml -i -o coverage_run.xml
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/conda-bld
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/locks
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/pkgs
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/var
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/conda-bld
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/locks
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/pkgs
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/var
