package:
  version: "{{ PROJECT_VERSION }}"
  name: 'roberto'

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps
  entry_points:
    - rob = roberto.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyyaml
    - invoke
    - importlib_resources  # [py<37]

test:
  requires:
    - pytest
  imports:
    - roberto
  commands:
    - pytest -v --pyargs roberto

about:
  dev_url: https://github.com/theochem/roberto
  description: Collection of configurable development workflows
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  home: https://github.com/theochem/roberto
  license_file: LICENSE.txt
  doc_url: https://github.com/theochem/roberto
