name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-venv:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.7
          - os: ubuntu-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.9
          - os: macos-latest
            python-version: 3.7

    runs-on: ${{ matrix.os }}
    env:
      # Tell Roberto to upload coverage results
      ROBERTO_UPLOAD_COVERAGE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: ~/.local/venvs
          key: ${{ runner.os }}-Python-${{ matrix.python-version }}-venv
      - name: Install Pip and Roberto
        run: |
          python -m pip install --upgrade pip
          pip install ./
      - name: Test Roberto with itself
        run: |
          if [[ -n "${GITHUB_HEAD_REF}" ]]; then
            ROBERTO_GIT_MERGE_BRANCH=${GITHUB_HEAD_REF} \
            ROBERTO_GIT_BRANCH=${GITHUB_BASE_REF} \
            rob
          else
            ROBERTO_TESTENV_USE=venv \
            rob robot
          fi


  test-conda:
    timeout-minutes: 30
    if: github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      ROBERTO_UPLOAD_COVERAGE: 1
      ROBERTO_PACKAGE_MANAGER: conda
      ROBERTO_TESTENV_USE: conda
      ROBERTO_DEPLOY_NOARCH: 1
      TWINE_USERNAME: theochem
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - uses: actions/cache@v2
        with:
          # There should be a nicer way that just hardcoding the path ...
          path: /usr/share/miniconda/envs
          key: ${{ runner.os }}-conda
      - name: Conda info
        run: conda info
      - name: Install Roberto
        run: |
          pip install ./
      - name: Test Roberto with itself
        run: |
          ROBERTO_CONDA_BASE_PATH=${CONDA} rob robot
